### ISSUE TITLE
No installation or compilation instructions

### ISSUE THREAD

**Issue by rodneyrod** [duxet/adium-facebook#1]

**Comment by duxet** [comment]
Hey @rodneyrod. There is a more important issue right now: there is no code to be compiled 😶

I tried to write some code, but i failed to compile it on 10.11.

**Comment by rodneyrod** [comment]
Fair call, I was having issues on 10.10 but it might be related to that.
I'll close this for now.

**Comment by duxet** [comment]
@rodneyrod: it seems that i just had pch file missing (it's not created automatically in newest version of xcode), so i will try to code something on weekend

**Comment by rodneyrod** [comment]
Awesome, thanks for that. Also, if you're able to generate an Adium plugin file, you should upload it to Adium Xtras so it'll be easier to access.

**Comment by duxet** [comment]
@rodneyrod I got some progress: it's working with newest Adium 1.7 branch, however i need to find why this plugin is not active on last released version.

**Comment by duxet** [comment]
@rodneyrod I can't activate my account on Adium Xtras, is it still working? 😶

**Comment by egorvinogradov** [comment]
Hi @duxet, can you please give an update on if this plugin is functional and can be used with Adium today? Thank you

**Comment by rodneyrod** [comment]
@duxet Ahh this is embarrassing, no it doesn't work. Sorry it took so long to report.

But I am still interested in getting this working so whenever you can provide a patch that would be great.

**Comment by egorvinogradov** [comment]
@rodneyrod I'm another guy but thanks!

**Comment by duxet** [comment]
Sorry for a such long time of response. I will try to update the library that is used to communicate with Messenger and add some instruction how to build the Adium extension.

**Comment by rodneyrod** [comment]
Closing this, moving the 'not compiling' issue to another ticket.
